[account]

# example: unlock = ["0x60cf8ebf54d4f8e93aa89a0b28469827f0df04b2"]
unlock = ["put your address here"]
password = ["password.txt"]

[ipc]
disable = true

[mining]
# example: engine_signer = "0x60cf8ebf54d4f8e93aa89a0b28469827f0df04b2"
engine_signer = "put your node address here"
force_sealing = true
min_gas_price = 1000
reseal_min_period = 0
reseal_on_txs = "none"
gas_floor_target = "300000000"

# for experienced users: adjust those settings for better performance.
tx_queue_size = 10240
tx_queue_mem_limit = 128
tx_queue_per_sender = 256
tx_queue_no_early_reject = true

[misc]
log_file = "diamond-node.log"
logging = "txqueue=info,consensus=info,engine=info,hbbft_message_memorium=error"
shutdown_on_missing_block_import = 700


[network]
interface = "all"
nat = "none"
port = 27272
reserved_peers = "reserved-peers"
# don't attempts to connect to non-public (~ local network) IPs (VM hosters do not like that)
allow_ips = "public"
max_peers = 48
min_peers = 27

[parity]
base_path = "data"
chain = "spec.json"

[rpc]
disable = true

[secretstore]
disable = true

[websockets]
disable = true

[footprint]
# TODO: set the maximum amount of memory, you can spare for this diamond-node.
# if no other services are running, you can set this value to almost all of your available RA 
# cache_size = 4096
