[account]

# example: unlock = ["0x60cf8ebf54d4f8e93aa89a0b28469827f0df04b2"]
unlock = ["put your address here"]
password = ["password.txt"]

[ipc]
disable = true

[mining]
# example: engine_signer = "0x60cf8ebf54d4f8e93aa89a0b28469827f0df04b2"
engine_signer = "put your node address here"
extra_data = "Parity"
force_sealing = true
gas_floor_target = "300000000"
min_gas_price = 1000000000
reseal_min_period = 0
reseal_on_txs = "none"

[misc]
log_file = "parity.log"
logging = "txqueue=info,consensus=info,engine=info,hbbft_message_memorium=error"

[network]
interface = "all"
nat = "none"
port = 40301
reserved_peers = "reserved-peers"
# don't attempts to connect to non-public (~ local network) IPs (VM hosters do not like that)
allow_ips = "public"
max_peers = 48
min_peers = 48

[parity]
base_path = "data"
chain = "spec.json"

[rpc]
disable = true

[secretstore]
disable = true

[websockets]
disable = true

